services:
  - type: web
    name: freelancing-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Backend/Dockerfile.render
    dockerContext: ./Backend
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: Freelancing-Platform-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: Freelancing-Platform-db
    databaseName: freelancing_platform
    user: freelancing_user
    plan: free
